name: alertxpro_app
description: App de alertas de preço (cripto)

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  http: ^1.2.0
  shared_preferences: ^2.5.5
  permission_handler: ^12.0.1

  flutter_local_notifications: ^18.0.1

  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1

  web_socket_channel: ^3.0.3

  # Pacotes para os Gráficos
  flutter_inappwebview: ^6.0.0
  candlesticks: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

# Configuração do Gerador de Ícones
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_icon_foreground.png" # <-- Alterado aqui!
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/