// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYZd8WbVRnTDtSAKhuOF0KWQ2NnVx1Ggo',
    appId: '1:176503712660:web:ed89b4ea259d2aed69bd81',
    messagingSenderId: '176503712660',
    projectId: 'alertx-pro-81046',
    authDomain: 'alertx-pro-81046.firebaseapp.com',
    storageBucket: 'alertx-pro-81046.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwT7EWMGAjmEZnyu2rWSIEAAjIKu0-XYE',
    appId: '1:176503712660:android:8c43105fc3596a0869bd81',
    messagingSenderId: '176503712660',
    projectId: 'alertx-pro-81046',
    storageBucket: 'alertx-pro-81046.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-1ZaKAAOQ8nQdDhdqQvLopWfyPFCFLbU',
    appId: '1:176503712660:ios:57fceb73facee02069bd81',
    messagingSenderId: '176503712660',
    projectId: 'alertx-pro-81046',
    storageBucket: 'alertx-pro-81046.firebasestorage.app',
    iosBundleId: 'dev.agassis.alertxpro.alertxproApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-1ZaKAAOQ8nQdDhdqQvLopWfyPFCFLbU',
    appId: '1:176503712660:ios:57fceb73facee02069bd81',
    messagingSenderId: '176503712660',
    projectId: 'alertx-pro-81046',
    storageBucket: 'alertx-pro-81046.firebasestorage.app',
    iosBundleId: 'dev.agassis.alertxpro.alertxproApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYZd8WbVRnTDtSAKhuOF0KWQ2NnVx1Ggo',
    appId: '1:176503712660:web:2e9843a83107560b69bd81',
    messagingSenderId: '176503712660',
    projectId: 'alertx-pro-81046',
    authDomain: 'alertx-pro-81046.firebaseapp.com',
    storageBucket: 'alertx-pro-81046.firebasestorage.app',
  );
}
